CREATE PROC FI_SP_IncBenef
    @NOME          VARCHAR (50) ,
    @IDCLIENTE     BIGINT,
    @CPF           VARCHAR (14)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, IDCLIENTE, CPF) 
	VALUES (@NOME, @IDCLIENTE, @CPF)

	SELECT SCOPE_IDENTITY()
END