CREATE PROC FI_SP_ConsBenef
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, IDCLIENTE, CPF, ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, IDCLIENTE, CPF, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END